artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/udeh-gideon/solar-radiation-forecasting-with-xgboost/raw/main/Nsukka_historical_weather_data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion